### ISSUE TITLE
請教萌典字體注音問題

### ISSUE THREAD

**Issue by Congan0711** [g0v/moedict-webkit#216]
唐老師您好：

我是華測會研發專員王從安，想請教有關萌典上顯示的中文含注音字體的顯示相關問題。
由於敝會最近推出了準備級試題的紙筆測驗，目前往電腦化測驗方向發展，但在研發過程中，發現｢王漢宗自由字型｣字體的少部份的注音錯誤（例如衣服、名字等輕聲），但根據萌典的版權說明中，萌典也是使用相同字體，但顯示均正確（符合教育部標準發音），想請教萌典的標楷注音字體是使用｢王漢宗自由字型｣中的字體嗎？還是另外引用其他字體，可提供敝會參考。

（本會的其他等級電腦化測驗因為題目不提供注音，僅提供標楷體中文，而準備級考試是針對Novice等級的華語學習者設計，故而一直以來未發現這個問題。）

懇請協助回答，謝謝您～

國家華語測驗推動工作委員會
研究發展組 王從安
新北市林口區仁愛路一段2號
（資訊與教學大樓Ｂ棟7樓）
電話：02-7714-8312
傳真：02-2601-4181
網址：www.sc-top.org.tw

**Comment by audreyt** [comment]
萌典的注音顯示技術並不依賴字型（王漢宗自由字型僅於「分享字圖」功能裡列為選項使用），而是以 @ethantw 開發的 `漢字標準格式` https://hanzi.pro/manual/yangshi_biaozhunhua#hangjianzhu_yuansu 框架為基礎，歡迎參考。

**Comment by Congan0711** [comment]
感謝您的回應，我會再會同敝會資訊同仁解決這個問題，若有問題再請教您。
