### ISSUE TITLE
連線時萌典 app 無法播放筆順動畫

### ISSUE THREAD

**Issue by caasi** [g0v/moedict-webkit#220]
在 fb 粉絲頁接到回到：

![2018-04-14 02 10 14](https://user-images.githubusercontent.com/1164470/38750921-10bb6dc8-3f89-11e8-8ea3-f01ac584b392.png)

但發現 au 在 4/4 [已經修正程式](https://github.com/g0v/moedict-webkit/commit/46d62ec6a49c1cd5fa3cc188d29ef3a31324da98)，也更新了 `manifest.appcache` 。

不知道我可以怎樣協助對方？

**Comment by audreyt** [comment]
今天我在萌典松會試著把 Android 版本更新，預計明天 deploy。

iOS 方面，我的 App Store 帳號（audrey.tang@socialtext.com）被鎖住了，正在和 apple support 連絡看能不能取回~

**Comment by caasi** [comment]
想問問現在的狀況。

另外是否有需要建立新帳號，並將 app 移轉過去？

順便請教 @wildjcrt, @miaoski 現在阿美語萌典的發佈方式，搞不好我可以效法。

**Comment by audreyt** [comment]
現在狀況是我的 Android keystore 和 Apple ID 都拿不回來（默）。

新的帳號是一條路。另一個方式是直接把萌典做成 PWA。

**Comment by wildjcrt** [comment]
阿美語萌典 iOS 也是請 au 幫忙發佈的。
Android 則是用 miaoski 帳號發佈的。
（好像沒有比較健康 XD）

**Comment by caasi** [comment]
😂

（把 PWA 放到待辦清單）

**Comment by audreyt** [comment]
最新進度：用另一個 Apple ID (me.com) 重新發佈了。第一次送出被退回，因為 description 寫「教育部」國/台/客語有聲辭典。已經把「教育部」三字拿掉，重新送出。

**Comment by audreyt** [comment]
更新進度： `國語、台語、客語有聲辭典` 第二次被退回，原因是 description 裡不能出現分隔關鍵字的頓號。以「開放多語有聲詞典」第三次提交發佈。
