### ISSUE TITLE
請益筆劃的資料

### ISSUE THREAD

**Issue by zhi8617** [g0v/moedict-webkit#221]
各位先鋒您們好
初次接觸，如有不熟還請見諒

我想請教的是筆劃的資料
看了moedict 的 info 提到 

> 筆劃資料來源為教育部「常用國字標準字體筆順學習網」，國語發音資料來源為教育部「國語辭典簡編本」（CC BY-ND 3.0 臺灣授權），著作權仍為教育部所有。

請問筆順資料目前這個專案已經收錄了嗎?
還是要去 「常用國字標準字體筆順學習網」 爬取資料呢 ??

看過了 moedict 網站 以及 github 的說明 好像都沒有這部份的資料
還請先鋒們提示 

感謝

**Comment by audreyt** [comment]
筆順資料在 https://github.com/g0v/zh-stroke-data

另可參考 https://github.com/g0v/react-zh-stroker
