### ISSUE TITLE
標點符號的 span 包含前一詞

### ISSUE THREAD

**Issue by m80126colin** [g0v/moedict-webkit#223]
剛剛在查詢字典時，發現 HTML 包含標點符號的 span.punct 底下有前一詞的 HTML 標籤，以[淘漉](http://www.moedict.org/#%E6%B7%98%E6%BC%89)第一點例句為例：

``` HTML
<span class="punct"><a href="./#的">的</a>，</span>
```

儘管不影響使用者，但想問問是否是預期的結果？

**Comment by audreyt** [comment]
這是預期的結果，目的是要避頭點（首字不要出現標點）。

```css
white-space: nowrap;
display:inline-block;
```
