### ISSUE TITLE
「唐」字 /pua/ 和 國語 /a/ 不同

### ISSUE THREAD

**Issue by ystsai** [g0v/moedict-webkit#229]
https://www.moedict.tw/pua/%E5%94%90

<img width="987" alt="screen shot 2018-09-25 at 8 28 39 pm" src="https://user-images.githubusercontent.com/7852263/46055606-a3152480-c101-11e8-9d1c-c721da8ef5c8.png">

https://www.moedict.tw/a/%E5%94%90.json

<img width="600" alt="screen shot 2018-09-25 at 8 29 21 pm" src="https://user-images.githubusercontent.com/7852263/46055621-b6c08b00-c101-11e8-82dc-1fa7dfae5172.png">

**Comment by audreyt** [comment]
這是 APFS High Sierra 的問題，已經在 Linux ext3 上重新執行 `link2pack.pl` 修復，感謝回報！
