### ISSUE TITLE
「歷代書體」出錯，顯示Not Found。

### ISSUE THREAD

**Issue by daixiaoluck** [g0v/moedict-webkit#236]
點選「筆順動畫」的圖示後出現的「歷代書體」按鈕顯示Not Found，具體情況請見附圖。
<img width="348" alt="capture" src="https://user-images.githubusercontent.com/10736725/51782451-7599bf80-2163-11e9-9a09-e83dd8c9488f.PNG">

**Comment by audreyt** [comment]
先前用 iframe 顯示 animated gif，是由於沒有 API。現在已經有了，應調整成直接使用 API：

http://bs.chinese-linguipedia.org/api/web/word/%E8%90%8C

JSON 裡的 key 是 `data.strokes`。

**Comment by daixiaoluck** [comment]
> 先前用 iframe 顯示 animated gif，是由於沒有 API。現在已經有了，應調整成直接使用 API：
> 
> http://bs.chinese-linguipedia.org/api/web/word/%E8%90%8C
> 
> JSON 裡的 key 是 `data.strokes`。

既然談到strokes，我就把本來打算新開一個issue的bug在這裏就告訴大大：
https://www.moedict.tw/%E6%84%B7 和 https://www.moedict.tw/%E8%9C%86 的「筆順動畫」都有問題。前者無法顯示筆順，後者的筆順明顯有錯。
大大能告知你使用哪個canvas library以顯示筆順嗎？
<img width="182" alt="capture2" src="https://user-images.githubusercontent.com/10736725/51800092-803c7d80-2265-11e9-9382-6d0b8d46ecd1.PNG">
<img width="184" alt="capture3" src="https://user-images.githubusercontent.com/10736725/51800096-8599c800-2265-11e9-9a4d-dfaa8f3f9a16.PNG">

**Comment by audreyt** [comment]
用的是 `react-zh-stroker`. 「蜆」的問題應該是之前試圖用部件組字不成功的殘留。

**Comment by caasi** [comment]
就像 au 所說，「蜆」是部件組字殘留資料造成的。

不幸的是，我一直沒把 `react-zh-stroker` 裝到 `moedict-webkit` 上，現在 master 用的還是 `zh-stroke-data` 的 [`jquery.stroke-words`](https://github.com/g0v/zh-stroke-data/tree/master/coffee) 。

我先修歷代書體，再來升級（或是不升級）筆順。
