### ISSUE TITLE
萌典網站的國語辭典和兩岸辭典皆不能用

### ISSUE THREAD

**Issue by daixiaoluck** [g0v/moedict-webkit#241]
萌典網站的國語辭典和兩岸辭典皆不能用。
Chrome的console中提示3個error，詳情見附圖。
<img width="941" alt="批注 2019-06-11 123648" src="https://user-images.githubusercontent.com/10736725/59244094-9c095480-8c45-11e9-9c9a-205a5f438bd8.png">

**Comment by audreyt** [comment]
Linode Tokyo 2 forced migration, 今晚應可恢復
