### ISSUE TITLE
目前可否用「臺羅」查詢？

### ISSUE THREAD

**Issue by jhs-tw** [g0v/moedict-webkit#242]
根據下面這篇 tweet，當時似乎可以用臺羅（臺灣羅馬字）拼音查詢字詞：
https://twitter.com/moedict/status/555667643663798272

但剛剛嘗試輸入 kok、ka 等，卻無法查詢。

**Comment by a-tsioh** [comment]
pháinn-sè !
service restarted

**Comment by jhs-tw** [comment]
多謝！

**Comment by jhs-tw** [comment]
似乎出了點狀況。

印象中，昨天嘗試的時候，在查詢欄位輸入 binatsai，會自動出現「明仔載」在下拉式選單中。剛剛嘗試，卻失敗了，如下圖。

![bin-a-tsai](https://user-images.githubusercontent.com/42627483/61024760-3db8c880-a3e1-11e9-9e3d-9686cfea4987.jpg)

但輸入 singlip，卻又正常出現「成立」、「省立」兩個候選詞，如下圖。

![sing-lip](https://user-images.githubusercontent.com/42627483/61025013-e49d6480-a3e1-11e9-954d-1d3ad04ef0eb.jpg)

**Comment by jhs-tw** [comment]
現在好像又不能用「臺羅」查詢了。
