### ISSUE TITLE
「岌岌可危」相似詞條目錯字

### ISSUE THREAD

**Issue by EnochLiou** [g0v/moedict-webkit#244]
[岌岌可危](https://www.moedict.tw/%E5%B2%8C%E5%B2%8C%E5%8F%AF%E5%8D%B1)
相似詞中的「搖搖欲墮」的最後一個字誤植，應為「墜」。
這連帶也使得這個條目無法正確連結到對應的「[搖搖欲墜](https://www.moedict.tw/%E6%90%96%E6%90%96%E6%AC%B2%E5%A2%9C)」詞條。

岌岌可危: https://www.moedict.tw/%E5%B2%8C%E5%B2%8C%E5%8F%AF%E5%8D%B1
搖搖欲墜: https://www.moedict.tw/%E6%90%96%E6%90%96%E6%AC%B2%E5%A2%9C

**Comment by audreyt** [comment]
http://dict.revised.moe.edu.tw/cgi-bin/cbdic/gsweb.cgi?o=dcbdic&searchid=Z00000087889 是上游的資料，請用該網頁「意見反應」功能回報，感謝！

感謝
鳳

________________________________
寄件者: EnochLiou <notifications@github.com>
寄件日期: 星期三, 7月 24, 2019 09:18
收件者: g0v/moedict-webkit
副本: Subscribed
主旨: [g0v/moedict-webkit] 「岌岌可危」相似詞條目錯字 (#244)


岌岌可危<https://www.moedict.tw/%E5%B2%8C%E5%B2%8C%E5%8F%AF%E5%8D%B1>
相似詞中的「搖搖欲墮」的最後一個字誤植，應為「墜」。
這連帶也使得這個條目無法正確連結到對應的「搖搖欲墜<https://www.moedict.tw/%E6%90%96%E6%90%96%E6%AC%B2%E5%A2%9C>」詞條。

岌岌可危: https://www.moedict.tw/%E5%B2%8C%E5%B2%8C%E5%8F%AF%E5%8D%B1
搖搖欲墜: https://www.moedict.tw/%E6%90%96%E6%90%96%E6%AC%B2%E5%A2%9C

**Comment by EnochLiou** [comment]
感謝提供回報窗口，已嘗試向資料來源單位以電郵方式回報。
