### ISSUE TITLE
新頁面顯示gsc.tab=0

### ISSUE THREAD

**Issue by SeanGau** [g0v/moedict-webkit#264]
開啟 moedict.tw 不帶入任何參數的時候，會顯示出gsc.tab=0

**Comment by caasi** [comment]
我還是會被導向到 https://www.moedict.tw/%E8%90%8C ，可以提供更清楚的重現步驟嗎？還有使用的是什麼瀏覽器？

**Comment by audreyt** [comment]
This is fixed in the GSC setting.
