### ISSUE TITLE
字圖：加入「源雲明體」

### ISSUE THREAD

**Issue by GJRobert** [g0v/moedict-webkit#268]
「就是字」的 But 對思源系列字型做的改版裡面，我覺得最好看的就是「源雲明體」：[ButTaiwan/genwan-font: A free font family derived from Source Han Serif.](https://github.com/ButTaiwan/genwan-font)

ChhoeTaigi 今年也改用了「源雲明體」。如果「字圖」加入這個字型應該袂䆀？

**Comment by audreyt** [comment]
https://www.moedict.tw/%E5%8A%A0%E5%85%A5%E9%80%99%E5%AD%97%E5%9E%8B%E6%87%89%E8%A9%B2%E6%98%AF%E8%A2%82%E4%86%80?font=gwmm

**Comment by GJRobert** [comment]
數位大臣 94 狂！
