### ISSUE TITLE
查不到「臺灣閩南語常用詞辭典」內有收錄的常用詞

### ISSUE THREAD

**Issue by miau715** [g0v/moedict-webkit#269]
台語「癩𰣻」一詞不知為何在萌典中無法查到，臺灣閩南語常用詞辭典之頁面在此：https://twblg.dict.edu.tw/holodict_new/result_detail.jsp?n_no=13127&curpage=1&sample=%E7%99%A9%F0%B0%A3%BB&radiobutton=1&querytarget=1&limit=20&pagenum=1&rowcount=5

**Comment by audreyt** [comment]
感謝，已經修正： https://www.moedict.tw/'%E7%99%A9%F0%B0%A3%BB

**Comment by oscarsun72** [comment]
剛才才發現「𰣻」是cjk-擴充G的字集（目前最新的擴充字集），大概是這個緣故吧。感恩感恩　讚歎讚歎　南無阿彌陀佛
