### ISSUE TITLE
「走精」注音錯誤

### ISSUE THREAD

**Issue by flamerecca** [g0v/moedict-webkit#298]
https://www.moedict.tw/'%E8%B5%B0%E7%B2%BE

應為「走ㄗㄠ 精ㄐㄧㄥ  tsau‑tsing」

**Comment by chin-u** [comment]
沒標錯喔
因爲是標本調  走 ㄗㄠˋ tsau 
但台語有變調  所以念 ㄗㄠ tsau
像火 本調 ㄏㄨㄟˋ hué
火車 標本調 ㄏㄨㄟˋ ㄑㄧㄚ hué-tshia
但念的時後變調 ㄏㄨㄟ ㄑㄧㄚ hue-tshia

https://twblg.dict.edu.tw/holodict_new/compile1_3_9_3.jsp

**Comment by lantw44** [comment]
> 像火 本調 ㄏㄨㄟˋ hué

這個應該是 ㄏㄨㆤˋ 喔，臺語沒有ㄟ。

**Comment by oscarsun72** [comment]
> 沒標錯喔 因爲是標本調 走 ㄗㄠˋ tsáu 但台語有變調 所以念 ㄗㄠ tsau 像火 本調 ㄏㄨㆤˋ hué 火車 標本調 ㄏㄨㆤˋㄑㄧㄚ hué-tshia 但念的時後變調 ㄏㄨㆤㄑㄧㄚ hue-tshia
> 
> 下面是教育部的變調說明 https://twblg.dict.edu.tw/holodict_new/compile1_3_9_3.jsp

菩薩慈悲：
或許可以用讀音與語音分別標注的方式處理。感恩感恩　南無阿彌陀佛

**Comment by lantw44** [comment]
> 或許可以用讀音與語音分別標注的方式處理。

這個不是讀音和語音的問題，而是標注本調還是變調的問題，如同「你好」要寫成「ㄋㄧˊ ㄏㄠˇ」還是「ㄋㄧˇ ㄏㄠˇ」的問題。目前注音的設計是標注本調，也就是寫成「ㄋㄧˇ ㄏㄠˇ」，但有些人可能覺得寫「ㄋㄧˊ ㄏㄠˇ」比較容易念出來。

**Comment by audreyt** [comment]
因為臺通拼音標的是變調，所以如果有參考變調的需求，可以考慮用「臺羅臺通共同顯示」：

<img width="463" alt="截圖 2022-02-04 上午12 54 12" src="https://user-images.githubusercontent.com/20723/152389765-1309d426-0691-4dc6-90fa-a77dd89bafdc.png">
