### ISSUE TITLE
許願：API查詢加入詞例

### ISSUE THREAD

**Issue by aphkyle** [g0v/moedict-webkit#302]
例如查詢“啊“
給出含有”啊“的詞語
謝謝

**Comment by github-world192** [comment]
這個功能本來就有了吧
給你參考ios 實作api 
https://medium.com/彼得潘的-swift-ios-app-開發教室/①①②一點點萌的字典-app-串接萌典-api-00c1bd06f09f

**Comment by aphkyle** [comment]
好吧謝謝
