### ISSUE TITLE
牒的解釋與「右師不廠對」

### ISSUE THREAD

**Issue by caasi** [g0v/moedict-webkit#309]
2020 年 7 月 fb 上， [林郁凱](https://business.facebook.com/MoeDict/posts/1179299502096142?comment_id=4800893203270069&__cft__[0]=AZV-Cg3i2Co96b6WMRY6gGhKWs0rzGU035nYWJE_PFxd_wC0sA62ucNtv8TtgBErcerxnLlLIFrvfmpeIW33oCos6bFRThCOepgK7rWs3v88U-dp7zS4poKpu85s6Jc85qNH-f9rXLv73M_J2iGhg9KzZD6dIskJZpMswnUzbZ8MDA&__tn__=R]-R) 說，「牒」字引用到的「右師不廠對，受牒而退。」應該是「右師不敢對，受牒而退。」，請問何者正確？

**Comment by oscarsun72** [comment]
當然是不敢對囉 不廠對何義？不通耳。
書證如下：
阮刻本：
https://ctext.org/library.pl?if=gb&file=98094&page=892#%E5%8F%97%E7%89%92%E8%80%8C%E9%80%80
武英殿本：
https://ctext.org/library.pl?if=gb&file=80242&page=35#%E5%8F%97%E7%89%92%E8%80%8C%E9%80%80
擬去《國語辭典》反應。萌典資料源自彼處者。
感恩感恩　南無阿彌陀佛

**Comment by oscarsun72** [comment]
菩薩慈悲： see 
![image](https://user-images.githubusercontent.com/30381714/166615316-48cf1ff1-36c4-4785-ac39-c2fcaec8678d.png)

感恩感恩　南無阿彌陀佛

**Comment by caasi** [comment]
謝謝您！那我先關閉這個 issue
