### ISSUE TITLE
有關 「聖母」的內容

### ISSUE THREAD

**Issue by patrikpalenik** [g0v/moedict-webkit#311]
https://www.moedict.tw/聖母
萌典有「聖母」詞，它的解釋，我只是針對第三個做點修正。

3. 天主教徒稱耶穌的母親瑪利亞為「聖母」。十字軍與騎士修道會奉其為守護神，並頌玫瑰經敬拜。

十字軍與騎士修道會沒有奉聖母（瑪利亞）為守護神，天主教是一神論，只有奉天主為神。天主教徒不稱呼聖人為守護神，頂多稱呼主保聖人。天主教徒不敬拜聖母，這是幾百年以來的大誤解，在那麼好的詞典寫這句更讓我難過。我建議修改以上的一句為：

3. 天主教徒稱耶穌的母親瑪利亞為「聖母」，並以某些敬禮尊敬她（並非敬拜）。

希望萌典編輯組能了解，如果代表某個宗教團體說話，就要用那宗教的說法。
感謝大家。辛苦了。
巴明志神父

**Comment by oscarsun72** [comment]
神父菩薩慈悲：
　　「萌典編輯組」應該是不存在的吧，因為它的資料全是取自《國語辭典》。因此內容問題，末學想還是去《國語辭典》意見反應來得實際。都會有及時的回覆的。阿門。感恩感恩　讚歎讚歎　聖母瑪利亞　南無阿彌陀佛
參考愚[此處回應帖](https://github.com/g0v/moedict-webkit/issues/309#issuecomment-1113378065)

https://dict.revised.moe.edu.tw/index.jsp
https://dict.revised.moe.edu.tw/qa.jsp

**Comment by patrikpalenik** [comment]
謝謝你們。
